# Generated by Django 5.1.6 on 2025-07-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, unique=True)),
                ('excerpt', models.TextField()),
                ('featured_image', models.URLField(max_length=500)),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('reading_time', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=50)),
                ('tags', models.JSONField()),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-date'],
            },
        ),
    ]
