# Generated by Django 5.1.6 on 2025-07-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_content_alter_blogpost_featured_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='reading_time',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='read_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
