# Generated by Django 5.1.6 on 2025-07-18 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_likes_count_project_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
